version: "3.8"

services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node
    restart: unless-stopped

    ports:
      - "14001:4001" # Swarm
      - "5001:5001" # API
      - "8081:8080" # Gateway

    volumes:
      - ipfs-data:/data/ipfs

    environment:
      IPFS_PROFILE: server

    command: [ "daemon", "--migrate=true" ]

volumes:
  ipfs-data:
